### ISSUE TITLE
Screwy Tank Config

### ISSUE THREAD

**Issue by CovertJaguar** [BobPalmer/USI_Core#12]
The Kontainer Tanks seem to have some kind of issue with the Firesplitter FuelSwitch Module.

Namely, the label doesn't match the contents and "Tank_07" seems to be a fuel option.

Additionally, the Cylindrical tanks don't support Karborundum, only the spherical ones do.

![2016-01-19_00003](https://cloud.githubusercontent.com/assets/1521970/12431797/43d39894-beac-11e5-86f0-a7077778eb6b.jpg)
![2016-01-19_00001](https://cloud.githubusercontent.com/assets/1521970/12431798/43d77a40-beac-11e5-97e4-467f812518c3.jpg)
![2016-01-19_00002](https://cloud.githubusercontent.com/assets/1521970/12431799/43db6fec-beac-11e5-833c-bdfdcf65c586.jpg)

**Comment by BobPalmer** [comment]
Looks to be sorted in the upcoming release
