### ISSUE TITLE
Cylindrical tank kontainers no longer have LF, LH2, and MonoProp as options.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/USI_Core#18]
The spherical ones still have those three options available though.

I did take a quick look and compare using notepad++ and didn't see any obvious differences like a typo or something, so, not sure what broke.

**Comment by LouisB3** [comment]
My error from adding the new resources - I left out texture references in the fuel switch. Addressed in #17

**Comment by BobPalmer** [comment]
Sorted
