### ISSUE TITLE
Kontainer tanks need some weight/fuel volume balancing, especially for LH2

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/USI_Core#19]
I don't know how to embed an album in here, so:

http://imgur.com/a/o1b0j

**Comment by BobPalmer** [comment]
Bear in mind the FTT ones are off, and Nertea's ratios are completely off from stock (which is about 8000L per ton).

**Comment by BobPalmer** [comment]
Actually... changed my mind a bit.  I'll tweak it to the density ratio vs the volume ratio for LF

**Comment by smjjames** [comment]
Sounds good for me.
