### ISSUE TITLE
Surface-attachable reactors

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/USI_Core#20]
Per the [forum discussion](http://forum.kerbalspaceprogram.com/index.php?/topic/122420-105-usi-core-reactors-and-kontainers-v015-updated-kontainers/&page=4#comment-2405697), requesting that reactors be made surface-attachable. The smallest reactor, in particular, is handy - but having to find a node to place it on is less handy.

**Comment by BobPalmer** [comment]
This will be in the next release.
